import type { Metadata, Viewport } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationLoadingProvider } from "@/contexts/NavigationLoadingContext";
import Navbar from "@/app/components/Header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Proud Bisaya Bai",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/images/pbb_hd_logo.webp", type: "image/webp" }],
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased w-full overflow-x-hidden`}
        suppressHydrationWarning
      >
        <NavigationLoadingProvider>
          <div className="flex w-full">
            <div
              className="flex-1 min-h-screen w-full"
              style={{
                paddingTop: "var(--navbar-height, 64px)",
                paddingRight: "var(--sidebar-width, 0px)",
                transition: "padding-right 200ms ease",
              }}
            >
              {children}
            </div>
          </div>
        </NavigationLoadingProvider>
      </body>
    </html>
  );
}
