import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@measured/puck/puck.css";
import Navbar from "@/app/components/Header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Proud Bisaya Bai",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/images/pbb_hd_logo.webp", type: "image/webp" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
        <div className="flex">
          <div
            className="flex-1 min-h-screen"
            style={{
              paddingTop: "var(--navbar-height, 64px)",
              paddingRight: "var(--sidebar-width, 0px)",
              transition: "padding-right 200ms ease",
            }}
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
